#!/bin/sh

./.github/workflows/docs/build-docs 1>out.txt 2>err.txt
cat out.txt err.txt
ERRS=`cat err.txt | grep -v "start-string without end-string"`
if [ ! -z $ERRS ]
then
    echo "Docs build failed."
    exit 1
fi
