#!/bin/bash

set -e

for file in $(ls python/*py | xargs -n 1 basename)
do
    echo "============================================================"
    echo "Checking: ${file}"
    echo "============================================================"
    name=`basename $file .py`
    # Generate the script
    p2j -o -t ${name}.ipynb python/${file}
done
